version: '3'
networks:
  mimi-net:
services:
  mimi-api:
    container_name: mimi-api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    build:
      context: ./
    networks:
      - mimi-net
    ports:
      - 4000:4000
  mimi-web:
    container_name: mimi-web
    build: ../mimi-web
    stdin_open: true
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - mimi-net

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - mimi-net

networks:
  mimi-net:
    driver: bridge
volumes:
  caddy_data:
  caddy_config:
